language: python
python:
 - '2.7'
 - '3.4'
 - '3.5'
 - '3.6'
 - '3.7'
install:
 - pip install .
 - pip install coveralls
services:
  - xvfb
script:
 - nosetests --with-coverage --cover-erase --cover-package=nestcheck
after_success:
 - coveralls
notifications:
  email:
    - e.higson@mrao.cam.ac.uk
